### ISSUE TITLE
Permissions bug on mobile preventing people from talking in private threads

### ISSUE THREAD

**Issue by otter-computer** [otter-computer/ModMailBot#6]
There's a permissions bug in the Discord mobile app that prevents people from talking in the private threads modmail creates. Some thoughts on how to mitigate: 

When a thread is created, give users a role that grants them perms to send messages in the modmail channel. This should allow them to (possibly) talk in the thread. Will need to auto-delete any messages in the main modmail channel that aren't from users with the staff role. Will then auto-remove this role when the modmail thread is archived. Can possibly track user ID in the thread title, regex for this when thread is archived, then remove role.

**Comment by Zigyy-love** [comment]
Sam body need a bottomless

**Comment by otter-computer** [comment]
I think this has been fixed with the new react mobile app.
